name: GoBuild

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Get Go version from go.mod
      id: go-version
      run: |
        GO_VERSION=$(grep '^go ' go.mod | awk '{print $2}')
        echo "GO_VERSION=${GO_VERSION}" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@main
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Get commit hash
      id: vars
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -v -o iFileGo-${{ env.COMMIT_HASH }}-windows.exe

    - name: Build for Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -v -o iFileGo-${{ env.COMMIT_HASH }}-linux

    - name: Upload Windows build output
      uses: actions/upload-artifact@main
      with:
        name: iFileGo-${{ env.COMMIT_HASH }}-windows
        path: iFileGo-${{ env.COMMIT_HASH }}-windows.exe

    - name: Upload Linux build output
      uses: actions/upload-artifact@main
      with:
        name: iFileGo-${{ env.COMMIT_HASH }}-linux
        path: iFileGo-${{ env.COMMIT_HASH }}-linux
