name: GoBuild

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4

    - name: Get branch name
      id: vars
      run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Build
      run: go build -v -o iFileGo-$GITHUB_REF_NAME

    - name: Test
      run: go test -v ./...

    - name: Archive build output
      run: |
        mkdir -p build
        mv iFileGo-$GITHUB_REF_NAME build/
        tar -czvf build_output.tar.gz build/

    - name: Upload build output
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: build_output.tar.gz
